services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: openrod_qdrant
    restart: always
    ports:
      - "6333:6333"  # REST API
      - "6334:6334"  # gRPC API
    volumes:
      - ./qdrant_data:/qdrant/storage
  postgres:
    image: postgres:latest
    container_name: openrod_postgres
    restart: always
    ports:
      - 2345:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    container_name: openrod_adminer
    ports:
      - "8282:8080"
    depends_on:
      - postgres
    environment:
      ADMINER_DEFAULT_SERVER: postgres